include_directories(orderbook matching simulator)
add_executable(mm_engine main.cpp orderbook/order_book.cpp matching/matching_engine.cpp simulator/market.cpp simulator/noise_trader.cpp simulator/fixed_spread_mm.cpp simulator/risk_engine.cpp simulator/feature_engine.cpp simulator/inventory_aware_mm.cpp simulator/volatility_adaptive_mm.cpp simulator/order_flow_aware_mm.cpp simulator/regime_adaptive_mm.cpp simulator/momentum_trader.cpp)
