#pragma once

#include "../orderbook/order.hpp"
#include "market.hpp"
#include <queue>
#include <vector>
#include <random>
#include <cmath>
#include <algorithm>

enum class GatewayActionType {
    SUBMIT_ORDER,
    CANCEL_ORDER,
    CANCEL_TRADER_ORDERS
};

struct GatewayAction {
    uint64_t arrival_time; // Virtual timestamp when action reaches the matching engine
    GatewayActionType type;
    Order order;
    uint64_t cancel_order_id;
    uint32_t trader_id;

    // Min-heap comparator (earliest arrival_time processed first)
    bool operator>(const GatewayAction& other) const {
        return arrival_time > other.arrival_time;
    }
};

/**
 * @brief Realistic Execution Latency and Jitter Queue
 * Models propagation delay and network jitter between trading participant and matching engine.
 * Orders and cancel requests are buffered in a priority queue by timestamp.
 */
class LatencyBuffer {
public:
    LatencyBuffer(double mean_latency_ms = 5.0, double jitter_stddev_ms = 2.0, uint64_t seed = 42)
        : mean_ms(mean_latency_ms), stddev_ms(jitter_stddev_ms), rng(seed), lat_dist(mean_latency_ms, jitter_stddev_ms) {}

    void submit_order(const Order& order, uint64_t current_time) {
        double delay = std::max(1.0, lat_dist(rng));
        uint64_t arrival = current_time + static_cast<uint64_t>(std::round(delay));
        queue.push({arrival, GatewayActionType::SUBMIT_ORDER, order, 0, order.trader_id});
    }

    void cancel_order(uint64_t order_id, uint32_t trader_id, uint64_t current_time) {
        double delay = std::max(1.0, lat_dist(rng));
        uint64_t arrival = current_time + static_cast<uint64_t>(std::round(delay));
        queue.push({arrival, GatewayActionType::CANCEL_ORDER, Order{}, order_id, trader_id});
    }

    void cancel_trader_orders(uint32_t trader_id, uint64_t current_time) {
        double delay = std::max(1.0, lat_dist(rng));
        uint64_t arrival = current_time + static_cast<uint64_t>(std::round(delay));
        queue.push({arrival, GatewayActionType::CANCEL_TRADER_ORDERS, Order{}, 0, trader_id});
    }

    /**
     * @brief Drains all actions that have arrived at or before current_time and executes them on the market.
     * @return All trades generated by order executions.
     */
    std::vector<Trade> drain_due_actions(Market& market, uint64_t current_time) {
        std::vector<Trade> all_trades;
        while (!queue.empty() && queue.top().arrival_time <= current_time) {
            GatewayAction action = queue.top();
            queue.pop();

            switch (action.type) {
                case GatewayActionType::SUBMIT_ORDER: {
                    auto trades = market.process_order(action.order);
                    all_trades.insert(all_trades.end(), trades.begin(), trades.end());
                    break;
                }
                case GatewayActionType::CANCEL_ORDER: {
                    market.cancel_order(action.cancel_order_id);
                    break;
                }
                case GatewayActionType::CANCEL_TRADER_ORDERS: {
                    market.cancel_orders_by_trader(action.trader_id);
                    break;
                }
            }
        }
        return all_trades;
    }

    size_t pending_actions_count() const {
        return queue.size();
    }

    double get_mean_latency_ms() const { return mean_ms; }
    double get_jitter_stddev_ms() const { return stddev_ms; }

private:
    double mean_ms;
    double stddev_ms;
    std::mt19937_64 rng;
    std::normal_distribution<double> lat_dist;
    std::priority_queue<GatewayAction, std::vector<GatewayAction>, std::greater<GatewayAction>> queue;
};
